apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: ${YOUR_APP_IMAGE}  # Use the same image as your main application
        command: ["/bin/sh", "-c"]
        args:
        - |
          cd /home/appuser
          ./scripts/migrate.sh up
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_HOST
          value: ${DB_HOST}
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: ${DB_NAME}
        - name: SSL_MODE
          value: "disable"
      restartPolicy: Never
  backoffLimit: 1 