// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ErpAccount struct {
	ID                 uuid.UUID       `json:"id"`
	UserID             uuid.UUID       `json:"user_id"`
	Title              string          `json:"title"`
	Type               string          `json:"type"`
	DefaultAccount     bool            `json:"default_account"`
	VerificationStatus json.RawMessage `json:"verification_status"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type ErpCatalog struct {
	ID          uuid.UUID      `json:"id"`
	MerchantID  uuid.UUID      `json:"merchant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	UpdatedBy   uuid.UUID      `json:"updated_by"`
}

type ErpCustomer struct {
	ID            uuid.UUID      `json:"id"`
	CustomerID    uuid.UUID      `json:"customer_id"`
	MerchantID    uuid.UUID      `json:"merchant_id"`
	Name          string         `json:"name"`
	Email         string         `json:"email"`
	Phone         sql.NullString `json:"phone"`
	Address       sql.NullString `json:"address"`
	LoyaltyPoints sql.NullInt32  `json:"loyalty_points"`
	DateOfBirth   sql.NullString `json:"date_of_birth"`
	Status        string         `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	CreatedBy     uuid.UUID      `json:"created_by"`
	UpdatedBy     uuid.UUID      `json:"updated_by"`
}

type ErpOrder struct {
	ID              uuid.UUID       `json:"id"`
	MerchantID      uuid.UUID       `json:"merchant_id"`
	CustomerDetails json.RawMessage `json:"customer_details"`
	OrderDetails    json.RawMessage `json:"order_details"`
	OrderItems      json.RawMessage `json:"order_items"`
	Metadata        json.RawMessage `json:"metadata"`
	Tracking        json.RawMessage `json:"tracking"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type ErpPaymentMethod struct {
	ID         uuid.UUID      `json:"id"`
	MerchantID uuid.UUID      `json:"merchant_id"`
	Name       string         `json:"name"`
	Type       string         `json:"type"`
	Commission float64        `json:"commission"`
	Details    sql.NullString `json:"details"`
	IsActive   bool           `json:"is_active"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	CreatedBy  uuid.UUID      `json:"created_by"`
	UpdatedBy  uuid.UUID      `json:"updated_by"`
}

type ErpProduct struct {
	ID          uuid.UUID       `json:"id"`
	MerchantID  uuid.UUID       `json:"merchant_id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Price       float64         `json:"price"`
	Currency    string          `json:"currency"`
	Sku         sql.NullString  `json:"sku"`
	Weight      sql.NullFloat64 `json:"weight"`
	Dimensions  sql.NullString  `json:"dimensions"`
	ImageUrl    sql.NullString  `json:"image_url"`
	Status      string          `json:"status"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	CreatedBy   uuid.UUID       `json:"created_by"`
	UpdatedBy   uuid.UUID       `json:"updated_by"`
}

type ErpWarehouse struct {
	ID          uuid.UUID      `json:"id"`
	MerchantID  uuid.UUID      `json:"merchant_id"`
	Name        string         `json:"name"`
	Location    string         `json:"location"`
	Capacity    int32          `json:"capacity"`
	IsActive    bool           `json:"is_active"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	UpdatedBy   uuid.UUID      `json:"updated_by"`
}
