// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type MerchantsAddress struct {
	ID             uuid.UUID      `json:"id"`
	MerchantID     uuid.UUID      `json:"merchant_id"`
	AddressType    string         `json:"address_type"`
	StreetAddress1 string         `json:"street_address_1"`
	StreetAddress2 sql.NullString `json:"street_address_2"`
	City           string         `json:"city"`
	Region         string         `json:"region"`
	PostalCode     sql.NullString `json:"postal_code"`
	Country        string         `json:"country"`
	IsPrimary      sql.NullBool   `json:"is_primary"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type MerchantsBankAccount struct {
	ID                     uuid.UUID      `json:"id"`
	MerchantID             uuid.UUID      `json:"merchant_id"`
	AccountHolderName      string         `json:"account_holder_name"`
	BankName               string         `json:"bank_name"`
	BankCode               string         `json:"bank_code"`
	BranchCode             sql.NullString `json:"branch_code"`
	AccountNumber          string         `json:"account_number"`
	AccountType            string         `json:"account_type"`
	Currency               string         `json:"currency"`
	IsPrimary              sql.NullBool   `json:"is_primary"`
	IsVerified             sql.NullBool   `json:"is_verified"`
	VerificationDocumentID uuid.NullUUID  `json:"verification_document_id"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type MerchantsContact struct {
	ID          uuid.UUID      `json:"id"`
	MerchantID  uuid.UUID      `json:"merchant_id"`
	ContactType string         `json:"contact_type"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	Email       string         `json:"email"`
	PhoneNumber string         `json:"phone_number"`
	Position    sql.NullString `json:"position"`
	IsVerified  sql.NullBool   `json:"is_verified"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type MerchantsDocument struct {
	ID              uuid.UUID      `json:"id"`
	MerchantID      uuid.UUID      `json:"merchant_id"`
	DocumentType    string         `json:"document_type"`
	DocumentNumber  sql.NullString `json:"document_number"`
	FileUrl         string         `json:"file_url"`
	FileHash        sql.NullString `json:"file_hash"`
	VerifiedBy      uuid.NullUUID  `json:"verified_by"`
	VerifiedAt      sql.NullTime   `json:"verified_at"`
	Status          string         `json:"status"`
	RejectionReason sql.NullString `json:"rejection_reason"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type MerchantsMerchant struct {
	ID                         uuid.UUID      `json:"id"`
	UserID                     uuid.UUID      `json:"user_id"`
	LegalName                  string         `json:"legal_name"`
	TradingName                sql.NullString `json:"trading_name"`
	BusinessRegistrationNumber string         `json:"business_registration_number"`
	TaxIdentificationNumber    string         `json:"tax_identification_number"`
	BusinessType               string         `json:"business_type"`
	IndustryCategory           sql.NullString `json:"industry_category"`
	IsBettingCompany           sql.NullBool   `json:"is_betting_company"`
	LotteryCertificateNumber   sql.NullString `json:"lottery_certificate_number"`
	WebsiteUrl                 sql.NullString `json:"website_url"`
	EstablishedDate            sql.NullTime   `json:"established_date"`
	CreatedAt                  time.Time      `json:"created_at"`
	UpdatedAt                  time.Time      `json:"updated_at"`
	Status                     string         `json:"status"`
}

type MerchantsSetting struct {
	MerchantID          uuid.UUID             `json:"merchant_id"`
	DefaultCurrency     string                `json:"default_currency"`
	DefaultLanguage     string                `json:"default_language"`
	CheckoutTheme       sql.NullString        `json:"checkout_theme"`
	EnableWebhooks      sql.NullBool          `json:"enable_webhooks"`
	WebhookUrl          sql.NullString        `json:"webhook_url"`
	WebhookSecret       sql.NullString        `json:"webhook_secret"`
	AutoSettlement      sql.NullBool          `json:"auto_settlement"`
	SettlementFrequency sql.NullString        `json:"settlement_frequency"`
	RiskSettings        pqtype.NullRawMessage `json:"risk_settings"`
	CreatedAt           time.Time             `json:"created_at"`
	UpdatedAt           time.Time             `json:"updated_at"`
}
