// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	CreatedBy         uuid.UUID      `json:"created_by"`
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	PublicKey         string         `json:"public_key"`
	SecretKey         string         `json:"secret_key"`
	CanWithdrawal     bool           `json:"can_withdrawal"`
	CanProcessPayment bool           `json:"can_process_payment"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	ExpiresAt         sql.NullTime   `json:"expires_at"`
	LastUsedAt        sql.NullTime   `json:"last_used_at"`
	IsActive          bool           `json:"is_active"`
	MerchantID        uuid.NullUUID  `json:"merchant_id"`
}
