FROM postgres:latest

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=Ashu.3.10
ENV POSTGRES_DB=stock

# Copy initialization scripts if needed
# COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
